### ISSUE TITLE
NextJS with App router documentation

### ISSUE THREAD

**Issue by castrolem** [Eppo-exp/node-server-sdk#48]
### Documentation enhancement request
Hey 👋 , I'm looking at using Eppo as part of a **NextJS 14** app that serves only Server components with some Client components. 

I followed most of the documentation for the Node SDK but it would be nicer to have more specific documentation around it. Cheers

**Comment by leoromanovsky** [comment]
Hi @castrolem - this repo is actively developed but I am sorry for missing your issue when you filled it. I'd love to learn more about what documentation you'd feel is useful for the server components. Do you have an example usage you could share that you probably figured out, but wish you had written here?

**Comment by castrolem** [comment]
Oh, excellent @greghuels! Thank you for the link!
